### ISSUE TITLE
add db queries to home page 

### ISSUE THREAD

**Issue by njons** [njons/up-for-grabs#3]
Users want a dynamic homepage 

- Make homepage grab all essential information from the database
- [ ] all categories
- [ ] all items 
- [ ] all item names, status 
- [ ] all images connected to each of the items
- [ ] all first names of the users that have selected an item
